version: '3.3'


services:
   db:
     image: mysql:5.7
     container_name: db_server
     networks:
        - wpsite
    
      
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: man42
       MYSQL_DATABASE: wordpress
       MYSQL_USER: manzanarak
       MYSQL_PASSWORD: man2542
      
      

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wp
     networks:
        - wpsite
    
     ports:
       - "8000:80"
     restart: always
     environment:
       
       WORDPRESS_DB_USER: manzanarak
       WORDPRESS_DB_PASSWORD: man2542
       WORDPRESS_DB_NAME: wordpress
       
     networks:
        - wpsite

networks:
  wpsite:

volumes:
    db_data: {}
    